### ISSUE TITLE
Pet food

### ISSUE THREAD

**Issue by AlexNiro** [TheSpartaPT/vrp_pets#4]
An error keeps throwing in the client console when i give my pet food.
![1](https://user-images.githubusercontent.com/51540191/59554308-b7f45980-8fa9-11e9-8ade-4ae7d704335c.PNG)

Hunger percentage works as the value changes when i give it food but this error keeps popping up everytime `vrp_pets:givefood` event gets called. 

Also, this part never gets triggered:
![2](https://user-images.githubusercontent.com/51540191/59554310-bd51a400-8fa9-11e9-8006-1dabde151c72.PNG)

**Comment by AlexNiro** [comment]
Found the problem, it's in client main.lua, lines 126, 133, 136, 139 they need to be defined as tables with { }.

**Comment by TheSpartaPT** [comment]
@AlexNiro you didn't find any problem, it's just that this script was made for a previous vRP version and it works perfectly for that version, the vRP guy updated it like a year ago and I just didn't want to waste time updating this, because it is pretty easy so everyone can do that, consider this repo deprecated I guess
